version: "3.8"
services:

  toy-bank:
    image: thedarkside/toy-bank:latest
    container_name: toy-bank
    ports:
      - 9022:8080
    environment:
      - MONGODB_URI=mongodb://root:password@mongo:27017
      - CACHING_SERVICE_ENDPOINT=http://toy-caching-service:8080/caching-service/cache
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans

networks:
  default:
    name: local-stack-network
    external: true


